# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
  gen:
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/compressURL"
        tables: "short_url,short_url_code"
        jsonCase: "CamelLower"
  # 工具编译配置
  build:
    name: "reURl"
    arch: "amd64"
    system: "linux,darwin,windows"
    mod: ""
    cgo: 0