version: '3'

services:
  mysql-db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: reURL-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
